spring.application.name=CozyNest


spring.datasource.url= jdbc:postgresql://localhost:5432/CozyNest
spring.datasource.username= postgres
spring.datasource.password= Vansh12lute

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8081
#by default every starting path
server.servlet.context-path=/api/v1

spring.security.user.name=vansh
spring.security.user.password=vansh

jwt.SecretKey=vaG4gRG9lIiwiaWF0IjoxNDIyfOiIxMjM0NTY3eyJzdWIi6IkpODkwIiwibmFtZSITE2MjM5MQ


stripe.successEvent.url=http://127.0.0.1:3000/success.html?vscode-livepreview=true
stripe.failEvent.url=http://127.0.0.1:3000/fail.html?vscode-livepreview=true
#Enter your own
#stripe.secret.key=