spring.application.name=CozyNest


spring.datasource.url= jdbc:postgresql://localhost:5432/CozyNest
spring.datasource.username= postgres
spring.datasource.password= Vansh12lute

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8081

